version: '3' 

services: 
    front:  
      image: frontend
      build: . 
      ports:
        - 5000:5000
    back:
      image: backend
      environment:
        - REDIS_HOST=redis
      build: . 
      ports:
        - 8080:8080
    redis:
      image: redis
      build: . 