version: '3.5' 

services:
    nginx:
      image: nginx
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
      - 80:80
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_DB: db
      container_name: db_test   
    front:  
      image: frontend
      build: . 
      ports:
        - 5000:5000
    back:
      image: backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=db
      build: . 
      ports:
        - 8080:8080
      depends_on:
      - db
    redis:
      image: redis
      build: .

   
